[package]
name = "qt5"
version = "1.0.0"  # 必须3位
authors = ["gzleo"]

[dependencies]
libc = "0.2"
libffi-sys = "0.6"

[features]
#default = [ "widgets" ]
#widgets = []
#network = []
#qml = []
#default = ["core"]
qtrt = []
core = []

